### ISSUE TITLE
Feature request: Operating on a read-only filesystem (with pre-created index)

### ISSUE THREAD

**Issue by jason-curtis** [libspatialindex/libspatialindex#236]
This is an upstream issue from https://github.com/Toblerity/rtree/issues/247.

In some cases I'd like to use libspatialindex with a read-only index file. One case is on AWS Lambda where source files are read-only. However `DiskStorageManager.cc` is explicitly checking that files are writeable, even if the user has no intention of updating them:
https://github.com/libspatialindex/libspatialindex/blob/3be67583852c741d0357f7ef5148c5fe8b484076/src/storagemanager/DiskStorageManager.cc#L170-L189

Would it be safe to remove the check for writeability (`std::ios::out`) at least in the case where `bFileExists` is `true` and `bOverwrite` is `false`? IMO it would be OK to fail later in the case where the user tries to modify the index but the filesystem is read-only.

**Comment by jmarrec** [comment]
Seems like flush(), which writes, is always called by the DiskStorageManager dtor.

**Comment by alhom** [comment]
Hi - I'm running into a similar issue with the Rtree package. It seems this issue was solved once, so I was thinking that surely this should now be possible to have working in Rtree... but the fix was reverted for some reason. Is there some underlying reason for there not being a read-only option for the disk-stored index?
